### ISSUE TITLE
Automatic Incident log

### ISSUE THREAD

**Issue by DreamsVoid** [bderenzo/tinystatus#18]
Hello,

I was wondering if having the incidents log automatically generate was something you were interested in?

And, if so this what sort of requirements would you have for it? 

For example:
- Design limits on storing the incidents between page generation
  - Tests are done within `/tmp` and are removed once the script exists, but you do have checks stored as a CSV file.
- How the incidents are presented
  - Would logging the exit code first and last occurrence within a time range be sufficient?
  - e.g. Google (Ping) 2021/07/15 08:00 - 2021/07/15 08:05
- How many would be presented as a maximum?
  - Anecdotally I added 50+ to a list and it did not look overly pleasing

**Comment by bderenzo** [comment]
Thank you for the help. The goal of the project is to display the state of services while remaining minimalist.
In my opinion, specific needs such as automatic logging of incident can be made according to the uses by users so I close the issue
