### ISSUE TITLE
Upcoming events?

### ISSUE THREAD

**Issue by jc-dgit** [bderenzo/tinystatus#19]
Looking over this, for one of our project's needs it's mostly just missing a way to display upcoming events (eg scheduled maintenance, changes, etc).

Any interest in a PR for adding that?

If so, I can put something together, likely modelled on the existing checks.csv.

**Comment by bderenzo** [comment]
The addition of upcoming events can be done easily on the model of the listing of the incidents. 
Add after line 8:
```
maintenancefile="${3:-maintenance.txt}"
```

And after line 121:
```
if [ -f "${maintenancefile}" ]; then
    echo '<h1>Schedule maintenance</h1>'
    if [ -s "${maintenancefile}" ]; then
        sed 's|^\(.*\)$|<p>\1</p>|' "${maintenancefile}"
    else
        echo '<p>No maintenance scheduled yet ;)</p>'
    fi
fi
```

In my opinion, specific needs such as this can be made according to the uses by users, so I close the issue.

**Comment by jc-dgit** [comment]
No worries. :smile:
