### ISSUE TITLE
Layout changes, HTML incidents, JavaScript to change status if page age > 5 min

### ISSUE THREAD

**Issue by thomasjsn** [bderenzo/tinystatus#22]
I've made several updates to my fork https://github.com/thomasjsn/tinystatus

* Layout changes
* Incidents have type and are HTML formatted
* Small JavaScript to set status to unknown if page was generated more than 5 mins ago

You want a pull request for any of these changes?

![image](https://user-images.githubusercontent.com/6061006/158019104-79a93bc0-7a9e-4087-ae52-e0e4a4933002.png)

**Comment by bderenzo** [comment]
The design is indeed nice. Thank you for the suggestions but the aim of tinystatus is to remain minimalist. 
For incidents, with your additions I think you should better replace the .txt with a .csv and use columns (one for incident type, one for date, etc.)
