### ISSUE TITLE
Script does not handle slash in check name

### ISSUE THREAD

**Issue by thomasdn** [bderenzo/tinystatus#26]
Steps to reproduce:

Edit checks.csv, add:

`port,   0,    Google DNS                    (tcp/53),             8.8.8.8 53`

Script will now produce error:

`tinystatus: line 45: /tmp/tmp.vrQmtcfIoZ/ok/Google DNS                    (tcp/53).status: No such file o
r directory`

I believe is caused by the fact that the script seems to use the check name string as the file name to store the status result. I think an easy way to fix this would be to do a hash of the name string and use as filename instead. For example: something like:

`echo "Status code: ${statuscode}" > "${tmp}/ok/${name}.status"`

would be changed into:

```
name_hash=hashname=$(echo -n "$name" | sha256sum | awk '{print $1}')
echo "Status code: ${statuscode}" > "${tmp}/ok/${name_hash}.status"
```

If sha256sum is not available, the script could fall back to sha1sum or even md5sum, cryptographic strengh is not too important here.

**Comment by bderenzo** [comment]
Thanks, the issue has been fixed.
