### ISSUE TITLE
Unable to make it works for subdomains like groups.google.com

### ISSUE THREAD

**Issue by shavidzet** [bderenzo/tinystatus#27]
Because it seems permissions are restricted to push my branch, I'm trying to provide a solution for subdomains:

instead of:
```bash
OUTAGES_COUNT="$(ls "${TMP_DIR}/"*.ko | wc -l)"
```

we need:
```bash
OUTAGES_COUNT="$(find "${TMP_DIR}" -type f -name '*.ko' | wc -l)"
```

- Replaced `ls` with `find` in the script to handle file counting.
- This change ensures that `.ko` files are correctly counted even if `TMP_DIR` contains directories with subdomains in their names.

This resolves issues with counting files when TMP_DIR paths include subdomains.

**Comment by bderenzo** [comment]
> Because it seems permissions are restricted to push my branch

Weird, pull requests are open. 

> This resolves issues with counting files when TMP_DIR paths include subdomains.

After checking, it seems that there are no problems with sub-domains.
There may be a problem if the check name contains a `/`, but there's no trivial solution for this case.
